baseurl = "http://myname7om.github.io/"
title = "Thomas Allan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "Tom"

[markup.highlight]
style = "github-dark"

[params]
  author = "Thomas Allan"
  info = ["Computer Science Graduate","Heriot Watt University"]
  description = "Thomas Allan's personal website"
  keywords = "blog,developer,personal"
 # avatarurl = "images/avatar.jpg"
 gravatar = "thomas119.allan@gmail.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/myname7om/"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://x.com/ThomasAllan274"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/thomas-allan-872215293/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "/contact/"
